// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/get-company-info.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/pages.ts
var SITE_URL = "https://patelimpex.com";
var SITE_PAGES = [
  {
    "route": "/about",
    "title": "About us"
  },
  {
    "route": "/careers",
    "title": "Careers"
  },
  {
    "route": "/community",
    "title": "Community"
  },
  {
    "route": "/contact",
    "title": "Contact"
  },
  {
    "route": "/delivery-shipping-policy",
    "title": "Delivery & Shipping Policy"
  },
  {
    "route": "/",
    "title": "Patel Impex | One operator every leg of the journey"
  },
  {
    "route": "/industries",
    "title": "Industries"
  },
  {
    "route": "/insights",
    "title": "Insights"
  },
  {
    "route": "/merchandises",
    "title": "Merchandises"
  },
  {
    "route": "/payment-policy",
    "title": "Payment Policy"
  },
  {
    "route": "/privacy-policy",
    "title": "Privacy Policy"
  },
  {
    "route": "/qhse",
    "title": "QHSE"
  },
  {
    "route": "/refund-returns-policy",
    "title": "Refund & Returns Policy"
  },
  {
    "route": "/services",
    "title": "Services"
  },
  {
    "route": "/terms-conditions",
    "title": "Terms & Conditions"
  },
  {
    "route": "/ai-news/global",
    "title": "Patel Impex"
  },
  {
    "route": "/insights/cost-optimised-and-speed-to-market-import-program-for-new-truck-launch-in-australia",
    "title": "Cost-Optimised and Speed to market Import Program for New Truck Launch in Australia"
  },
  {
    "route": "/insights/global-shipping-rates-soar-as-retailers-race-to-beat-looming-tariffs",
    "title": "Global shipping rates soar as retailers race to beat looming tariffs"
  },
  {
    "route": "/insights/grid-scale-battery-project-logistics-delivery-for-renewable-energy-infrastructure",
    "title": "Grid-Scale Battery Project Logistics Delivery for Renewable Energy Infrastructure"
  },
  {
    "route": "/insights/major-fleet-wide-fuel-efficiency-agreement-signals-ongoing-focus-on-shipping-performance-and-decarbonisation",
    "title": "Major Fleet-Wide Fuel Efficiency Agreement Signals Ongoing Focus on Shipping Performance and Decarbonisation"
  },
  {
    "route": "/insights/reduced-import-delays-storage-costs-across-700-containers",
    "title": "Reduced Import Delays & Storage Costs Across 700+ Containers"
  },
  {
    "route": "/insights/south-east-asia-now-making-the-rates-running",
    "title": "South East Asia Now Making the Rates Running"
  },
  {
    "route": "/insights/time-critical-oversized-sewer-tank-delivery-to-residential-estate-development",
    "title": "Time-Critical Oversized Sewer Tank Delivery to Residential Estate Development"
  },
  {
    "route": "/insights/typhoon-rips-roofs-off-buildings-and-floods-southern-china",
    "title": "Typhoon Rips Roofs Off Buildings and Floods Southern China"
  },
  {
    "route": "/insights/typhoon-signal-unlikely-in-hong-kong-this-weekend-as-flights-to-japan-cancelled",
    "title": "Typhoon Signal Unlikely in Hong Kong This Weekend as Flights to Japan Cancelled"
  },
  {
    "route": "/insights/us-announces-new-tariffs-on-more-than-60-trading-partners",
    "title": "US Announces New Tariffs on More Than 60 Trading Partners"
  },
  {
    "route": "/product/aircraft-keychain",
    "title": "Patel Impex"
  },
  {
    "route": "/product/baseball-cap",
    "title": "Patel Impex"
  },
  {
    "route": "/product/beanie",
    "title": "Patel Impex"
  },
  {
    "route": "/product/bottle-opener-keychain",
    "title": "Patel Impex"
  },
  {
    "route": "/product/ceramic-mug",
    "title": "Patel Impex"
  },
  {
    "route": "/product/folding-camping-chair",
    "title": "Patel Impex"
  },
  {
    "route": "/product/ship-keychain",
    "title": "Patel Impex"
  },
  {
    "route": "/product/stainless-steel-water-bottle",
    "title": "Patel Impex"
  },
  {
    "route": "/product/straw-tote-bag",
    "title": "Patel Impex"
  },
  {
    "route": "/product/stubby-holder-1",
    "title": "Patel Impex"
  },
  {
    "route": "/product/truck-keychain",
    "title": "Patel Impex"
  },
  {
    "route": "/product/united-carriers-canvas-tote-bag",
    "title": "Patel Impex"
  },
  {
    "route": "/product/united-carriers-logo-fabric-patch-gsvwb",
    "title": "Patel Impex"
  }
];

// src/lib/mcp/tools/get-company-info.ts
var COMPANY = {
  name: "Patel Impex",
  summary: "Patel Impex is an India-based agro commodity exporter and end-to-end trade logistics operator, handling sourcing, quality control, packing, documentation and shipping.",
  website: SITE_URL,
  email: "contact@patelimpex.com",
  phone: "+91 79841 33417",
  locations: [
    { label: "Head office", address: "Rajkot, Gujarat, India" },
    { label: "Warehouse & packing unit", address: "Rajkot, Gujarat, India" },
    { label: "Logistics desk", address: "Mundra Port, Gujarat, India" },
    { label: "Shipping desk", address: "Nhava Sheva (JNPT), Mumbai, India" }
  ]
};
var get_company_info_default = defineTool({
  name: "get_company_info",
  title: "Get company & contact info",
  description: "Get Patel Impex's published company details: business summary, email, phone number and office locations.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(COMPANY, null, 2) }],
    structuredContent: COMPANY
  })
});

// src/lib/mcp/tools/get-page.ts
import { defineTool as defineTool2, ToolError } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^4.4.3";
function htmlToText(html) {
  return html.replace(/<script[\s\S]*?<\/script>/gi, " ").replace(/<style[\s\S]*?<\/style>/gi, " ").replace(/<svg[\s\S]*?<\/svg>/gi, " ").replace(/<[^>]+>/g, " ").replace(/&nbsp;/g, " ").replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/[ \t]+/g, " ").replace(/\s*\n\s*/g, "\n").trim();
}
var get_page_default = defineTool2({
  name: "get_page",
  title: "Read a website page",
  description: "Fetch the readable text content of one public Patel Impex website page. Pass a route from list_pages, for example '/services' or '/'.",
  inputSchema: {
    route: z.string().trim().min(1).describe("Page route from list_pages, e.g. '/about'. Use '/' for the home page.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ route }) => {
    const normalized = route.startsWith("/") ? route : `/${route}`;
    const page = SITE_PAGES.find((p) => p.route === normalized);
    if (!page) {
      throw new ToolError(
        `Unknown route "${normalized}". Call list_pages to see the available routes.`
      );
    }
    const url = `${SITE_URL}${normalized === "/" ? "" : normalized}`;
    const response = await fetch(url, { headers: { Accept: "text/html" } });
    if (!response.ok) {
      throw new ToolError(`Could not load ${url} (HTTP ${response.status}).`);
    }
    const text = htmlToText(await response.text()).slice(0, 2e4);
    return {
      content: [{ type: "text", text: `# ${page.title}
${url}

${text}` }],
      structuredContent: { route: normalized, title: page.title, url, text }
    };
  }
});

// src/lib/mcp/tools/list-pages.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
var list_pages_default = defineTool3({
  name: "list_pages",
  title: "List website pages",
  description: "List every public page on the Patel Impex website with its route and title. Use this to discover what content is available before calling get_page.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const pages = SITE_PAGES.map((page) => ({
      ...page,
      url: `${SITE_URL}${page.route === "/" ? "" : page.route}`
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(pages, null, 2) }],
      structuredContent: { count: pages.length, pages }
    };
  }
});

// src/lib/mcp/tools/search-site.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^4.4.3";
var search_site_default = defineTool4({
  name: "search_pages",
  title: "Search website pages",
  description: "Find Patel Impex website pages whose route or title matches a keyword. Returns matching routes to read with get_page.",
  inputSchema: {
    query: z2.string().trim().min(1).describe("Keyword to match, e.g. 'services' or 'policy'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ query }) => {
    const needle = query.toLowerCase();
    const matches = SITE_PAGES.filter(
      (page) => page.route.toLowerCase().includes(needle) || page.title.toLowerCase().includes(needle)
    ).map((page) => ({
      ...page,
      url: `${SITE_URL}${page.route === "/" ? "" : page.route}`
    }));
    return {
      content: [
        {
          type: "text",
          text: matches.length ? JSON.stringify(matches, null, 2) : `No pages matched "${query}". Call list_pages to see every route.`
        }
      ],
      structuredContent: { count: matches.length, matches }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "patelimpex",
  title: "patelimpex",
  version: "0.1.0",
  instructions: "Read-only tools for the Patel Impex website (agro commodity export and trade logistics, India). Use `list_pages` or `search_pages` to find a page route, `get_page` to read that page's text, and `get_company_info` for published contact details. All data is public website content.",
  tools: [list_pages_default, search_site_default, get_page_default, get_company_info_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
