// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lhgtjjmqpzusaibapsvg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxoZ3Rqam1xcHp1c2FpYmFwc3ZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MDI2MDksImV4cCI6MjA3MjM3ODYwOX0.VsvRIpC09PH4ZOHt-0ZJEOTFyJk-RZtVe3KgvJi1SVg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});